services:
  api:
    build: .
    container_name: fastify-api
    working_dir: /app
    volumes:
      - .:/app
    networks:
      - fastify_network
    ports:
      - "2000:2000"
  redis:
   image: 'redis:7.4'
   networks: 
    - fastify_network
   volumes:
    - redis_data:/data
   ports:
    - '6379:6379'

  db:
   image: postgres:17-alpine
   tty: true
   environment:
    POSTGRES_USER: root
    POSTGRES_DB: fastifyDb
    POSTGRES_PASSWORD: docker
   volumes:
     - postgres_volume_data:/var/lib/postgresql/data
   networks:
    - fastify_network

networks:
  fastify_network:
    driver: bridge

volumes:
  postgres_volume_data: {}
  redis_data: {}